import { ClinicWithDetails } from '@/lib/services/clinics';

export const MOCK_CLINICS: ClinicWithDetails[] = [
    {
        id: '1',
        name: 'Yazd Heart Center',
        description: 'Specialized cardiology clinic',
        address: '123 Health St',
        city: 'Yazd',
        province: 'Yazd',
        country: 'Iran',
        phone: '123-456-7890',
        image: 'https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?auto=format&fit=crop&q=80&w=1000',
        website: 'https://yazdheart.com',
        isVerified: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        averageRating: 4.5,
        reviewCount: 120,
        isFavorited: false,
        services: [
            {
                id: 's1',
                name: 'Cardiology Consultation',
                description: 'General checkup',
                priceMin: 5000000,
                priceMax: 7000000,
                currency: 'IRR',
                clinicId: '1',
                categoryId: 'c1',
                createdAt: new Date(),
                updatedAt: new Date(),
                category: { name: 'Cardiology' }
            }
        ],
    },
    {
        id: '2',
        name: 'Tehran General Hospital',
        description: 'Comprehensive medical services',
        address: '456 Main Blvd',
        city: 'Tehran',
        province: 'Tehran',
        country: 'Iran',
        phone: '021-12345678',
        image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=1000',
        website: 'https://tehrangh.com',
        isVerified: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        averageRating: 4.8,
        reviewCount: 85,
        isFavorited: true,
        services: [],
    },
    {
        id: '3',
        name: 'Shiraz Dermatology Clinic',
        description: 'Skin care and laser treatments',
        address: '789 Saadi St',
        city: 'Shiraz',
        province: 'Fars',
        country: 'Iran',
        phone: '071-98765432',
        image: 'https://images.unsplash.com/photo-1516549655169-df83a092fc43?auto=format&fit=crop&q=80&w=1000',
        website: 'https://shirazskin.com',
        isVerified: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        averageRating: 3.9,
        reviewCount: 42,
        isFavorited: false,
        services: [],
    }
];
