import type { Clinic, Insurance, Specialty, Service } from '@prisma/client';

export interface MockClinic extends Clinic {
  specialties: Partial<Specialty>[];
  insurances: Partial<Insurance>[];
  serviceCategories: string[];
  rating: number;
  reviewCount: number;
  nextAvailable: string;
  waitTime: string;
  cost: string;
}

export const MOCK_CLINICS: MockClinic[] = [
  {
    id: '1',
    name: 'Tehran Heart Center',
    description: 'Leading cardiovascular center in the region.',
    address: 'North Kargar St.',
    city: 'Tehran',
    province: 'Tehran',
    country: 'Iran',
    phone: '+98 21 8802 9600',
    image: 'https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?auto=format&fit=crop&q=80&w=1000',
    website: 'https://thc.tums.ac.ir',
    isVerified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    rating: 4.8,
    reviewCount: 1240,
    nextAvailable: 'Tomorrow',
    waitTime: '15 mins',
    cost: '$20 - $50',
    specialties: [{ name: 'Cardiology' }, { name: 'Surgery' }],
    insurances: [{ name: 'Tamin' }, { name: 'Salamat' }],
    serviceCategories: ['Consultation', 'Surgery', 'Diagnostics'],
  },
  {
    id: '2',
    name: 'Milad Hospital',
    description: 'Comprehensive general hospital with advanced facilities.',
    address: 'Hemmat Expressway',
    city: 'Tehran',
    province: 'Tehran',
    country: 'Iran',
    phone: '+98 21 8409 0',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=1000',
    website: 'https://milad.ir',
    isVerified: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    rating: 4.2,
    reviewCount: 850,
    nextAvailable: 'In 3 days',
    waitTime: '45 mins',
    cost: '$15 - $40',
    specialties: [{ name: 'General' }, { name: 'Internal Medicine' }, { name: 'Orthopedics' }],
    insurances: [{ name: 'Tamin' }, { name: 'NiroohayeMosallah' }],
    serviceCategories: ['Emergency', 'Inpatient', 'Outpatient'],
  },
  {
    id: '3',
    name: 'Shiraz Central Clinic',
    description: 'Specialized clinic for dermatology and cosmetic procedures.',
    address: 'Zand St.',
    city: 'Shiraz',
    province: 'Fars',
    country: 'Iran',
    phone: '+98 71 3233 4455',
    image: 'https://images.unsplash.com/photo-1516549655169-df83a092fc43?auto=format&fit=crop&q=80&w=1000',
    website: 'https://shirazclinic.com',
    isVerified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    rating: 4.9,
    reviewCount: 320,
    nextAvailable: 'Today',
    waitTime: '10 mins',
    cost: '$30 - $80',
    specialties: [{ name: 'Dermatology' }, { name: 'Cosmetic' }],
    insurances: [{ name: 'Salamat' }],
    serviceCategories: ['Laser', 'Botox', 'Skin Care'],
  },
  {
    id: '4',
    name: 'Isfahan Eye Clinic',
    description: 'Premier eye care facility with state-of-the-art technology.',
    address: 'Chaharbagh Abbasi',
    city: 'Isfahan',
    province: 'Isfahan',
    country: 'Iran',
    phone: '+98 31 3222 1122',
    image: 'https://images.unsplash.com/photo-1579684385136-137af75461bb?auto=format&fit=crop&q=80&w=1000',
    website: null,
    isVerified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    rating: 4.7,
    reviewCount: 560,
    nextAvailable: 'Next Week',
    waitTime: '20 mins',
    cost: '$25 - $60',
    specialties: [{ name: 'Ophthalmology' }],
    insurances: [{ name: 'Tamin' }, { name: 'Salamat' }, { name: 'NiroohayeMosallah' }],
    serviceCategories: ['Surgery', 'Optometry'],
  },
  {
    id: '5',
    name: 'Tabriz Children Hospital',
    description: 'Dedicated pediatric care for children of all ages.',
    address: 'Sheshgelan',
    city: 'Tabriz',
    province: 'East Azerbaijan',
    country: 'Iran',
    phone: '+98 41 3526 2000',
    image: 'https://images.unsplash.com/photo-1538108149393-fbbd8189718c?auto=format&fit=crop&q=80&w=1000',
    website: null,
    isVerified: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    rating: 4.6,
    reviewCount: 410,
    nextAvailable: 'Tomorrow',
    waitTime: '30 mins',
    cost: '$10 - $30',
    specialties: [{ name: 'Pediatrics' }],
    insurances: [{ name: 'Tamin' }, { name: 'Salamat' }],
    serviceCategories: ['Vaccination', 'Checkups', 'Emergency'],
  },
];
