import type { Clinic } from '@prisma/client';

export interface MockClinic extends Clinic {
  specialties: string[];
  insurances: string[];
  serviceCategories: string[];
  rating: number;
  cost: string;
  waitTime: string;
  nextAvailable: string;
}

export const MOCK_CLINICS: MockClinic[] = [
  {
    id: '1',
    name: 'Tehran Heart Center',
    city: 'Tehran',
    province: 'Tehran',
    country: 'Iran',
    address: 'North Kargar Street, Tehran',
    phone: '+98 21 8802 9600',
    website: 'https://thc.tums.ac.ir',
    image: 'https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?auto=format&fit=crop&q=80&w=1000',
    isVerified: true,
    rating: 4.8,
    specialties: ['Cardiology', 'Surgery'],
    insurances: ['Tamin', 'Salamat', 'NiroohayeMosallah'],
    serviceCategories: ['Consultation', 'Surgery', 'Imaging'],
    cost: '$$',
    waitTime: '2 weeks',
    nextAvailable: 'In 3 days',
    createdAt: new Date(),
    updatedAt: new Date(),
    adminId: 'admin1',
    status: 'VERIFIED',
    description: 'Specialized heart center providing comprehensive cardiac care.',
    latitude: 35.7090,
    longitude: 51.3910,
    slug: 'tehran-heart-center',
    email: 'info@thc.tums.ac.ir',
    metadata: {},
  },
  {
    id: '2',
    name: 'Milad Hospital',
    city: 'Tehran',
    province: 'Tehran',
    country: 'Iran',
    address: 'Hemmat Expressway, Tehran',
    phone: '+98 21 8203 9',
    website: 'https://milad.ir',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=1000',
    isVerified: false,
    rating: 4.2,
    specialties: ['General', 'Internal Medicine', 'Neurology'],
    insurances: ['Tamin', 'Salamat'],
    serviceCategories: ['Emergency', 'Inpatient', 'Outpatient'],
    cost: '$',
    waitTime: '1 month',
    nextAvailable: 'Next week',
    createdAt: new Date(),
    updatedAt: new Date(),
    adminId: 'admin2',
    status: 'PENDING',
    description: 'Large public hospital offering a wide range of medical services.',
    latitude: 35.7448,
    longitude: 51.3753,
    slug: 'milad-hospital',
    email: 'info@milad.ir',
    metadata: {},
  },
  {
    id: '3',
    name: 'Shiraz Central Clinic',
    city: 'Shiraz',
    province: 'Fars',
    country: 'Iran',
    address: 'Zand Street, Shiraz',
    phone: '+98 71 3233 4455',
    website: 'https://shirazclinic.com',
    image: 'https://images.unsplash.com/photo-1516549655169-df83a092fc43?auto=format&fit=crop&q=80&w=1000',
    isVerified: true,
    rating: 4.6,
    specialties: ['Dermatology', 'Cosmetic'],
    insurances: ['Salamat'],
    serviceCategories: ['Consultation', 'Laser', 'Surgery'],
    cost: '$$$',
    waitTime: '1 week',
    nextAvailable: 'Tomorrow',
    createdAt: new Date(),
    updatedAt: new Date(),
    adminId: 'admin3',
    status: 'VERIFIED',
    description: 'Premier clinic for dermatology and cosmetic procedures.',
    latitude: 29.5918,
    longitude: 52.5837,
    slug: 'shiraz-central-clinic',
    email: 'contact@shirazclinic.com',
    metadata: {},
  },
    {
    id: '4',
    name: 'Isfahan Neuro Center',
    city: 'Isfahan',
    province: 'Isfahan',
    country: 'Iran',
    address: 'Amadegah Street, Isfahan',
    phone: '+98 31 3222 1111',
    website: 'https://isfahan-neuro.ir',
    image: 'https://images.unsplash.com/photo-1516549655169-df83a092fc43?auto=format&fit=crop&q=80&w=1000', // Reusing image
    isVerified: true,
    rating: 4.9,
    specialties: ['Neurology'],
    insurances: ['Tamin', 'NiroohayeMosallah'],
    serviceCategories: ['Consultation', 'EEG', 'EMG'],
    cost: '$$',
    waitTime: '3 weeks',
    nextAvailable: 'In 5 days',
    createdAt: new Date(),
    updatedAt: new Date(),
    adminId: 'admin4',
    status: 'VERIFIED',
    description: 'Specialized center for neurological disorders.',
    latitude: 32.6546,
    longitude: 51.6680,
    slug: 'isfahan-neuro-center',
    email: 'info@isfahan-neuro.ir',
    metadata: {},
  }
];
