
import { describe, it, expect, afterEach, mock } from "bun:test";
import React from "react";
import { render, cleanup } from "@testing-library/react";
import CompareTable from "./CompareTable";

// Mock next/image
mock.module("next/image", () => ({
    __esModule: true,
    // eslint-disable-next-line
    default: ({ fill, ...props }: any) => <img {...props} />
}));

// Mock clinic data
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const mockClinics: any[] = [
    {
        id: "c1",
        name: "Clinic One",
        city: "City A",
        province: "Prov A",
        image: "/img1.jpg",
        averageRating: 4.5,
        reviewCount: 10,
        services: [{ id: "s1", name: "Service A" }],
        translations: [],
        reviews: [],
        // details will be generated inside the component
    },
    {
        id: "c2",
        name: "Clinic Two",
        city: "City B",
        province: "Prov B",
        image: null, // Test fallback
        averageRating: 3.0,
        reviewCount: 5,
        services: [{ id: "s2", name: "Service B" }],
        translations: [],
        reviews: [],
    }
];

describe("CompareTable", () => {
    afterEach(() => {
        cleanup();
    });

    it("renders table headers", () => {
        render(<CompareTable clinics={mockClinics} />);
        const html = document.body.innerHTML;
        expect(html).toContain("Clinic");
        expect(html).toContain("Rating &amp; Wait");
        expect(html).toContain("Next Available");
        expect(html).toContain("Estimated Cost");
        expect(html).toContain("Services");
    });

    it("renders clinic names", () => {
        render(<CompareTable clinics={mockClinics} />);
        const html = document.body.innerHTML;
        expect(html).toContain("Clinic One");
        expect(html).toContain("Clinic Two");
    });

    it("renders visualizer content", () => {
        render(<CompareTable clinics={mockClinics} />);
        const html = document.body.innerHTML;
        // Check for wait time text generated by RatingVisualizer
        expect(html).toContain("Avg. Wait");
        // Check for Service names
        expect(html).toContain("Service A");
        expect(html).toContain("Service B");
    });

    it("renders empty state", () => {
        render(<CompareTable clinics={[]} />);
        expect(document.body.innerHTML).toContain("No clinics selected for comparison.");
    });
});
