name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    env:
      DATABASE_URL: postgresql://dummy:dummy@localhost:5432/dummy
      NEXTAUTH_SECRET: supersecret
      NEXTAUTH_URL: http://localhost:3000

    steps:
    - uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Generate Prisma Client
      run: bun x prisma generate

    - name: Run Linter
      run: bun run lint

    - name: Type Check
      run: bun x tsc --noEmit

    - name: Run Tests
      run: bun run test

    - name: Build
      run: bun run build
